/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Score = IDL.Nat;

export const idlService = IDL.Service({
  'addScore' : IDL.Func([IDL.Nat], [], []),
  'getScore' : IDL.Func([], [Score], ['query']),
  'getTopScores' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Score))],
      ['query'],
    ),
  'resetScore' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Score = IDL.Nat;
  
  return IDL.Service({
    'addScore' : IDL.Func([IDL.Nat], [], []),
    'getScore' : IDL.Func([], [Score], ['query']),
    'getTopScores' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Score))],
        ['query'],
      ),
    'resetScore' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };